# Generated by Django 3.1.7 on 2021-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lor',
            name='requester',
            field=models.EmailField(max_length=100),
        ),
    ]
