# Generated by Django 3.1.7 on 2021-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0003_auto_20210330_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='writer_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
