# Generated by Django 3.1.7 on 2021-03-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0003_auto_20210314_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lor',
            old_name='name',
            new_name='requester',
        ),
        migrations.RenameField(
            model_name='lor',
            old_name='writer',
            new_name='writer_email',
        ),
    ]
