# Generated by Django 3.1.7 on 2021-03-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0004_auto_20210314_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lor',
            name='company_website',
            field=models.URLField(),
        ),
    ]