# Generated by Django 3.1.7 on 2021-04-04 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LOR', '0004_auto_20210404_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='requester_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requestmodel_requester_id', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='writer_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_requestmodel_writer_id', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 11, 55, 6, 592136)),
        ),
    ]
