# Generated by Django 3.1.7 on 2021-04-04 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0013_auto_20210404_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 16, 56, 55, 984537)),
        ),
    ]
