# Generated by Django 3.1.7 on 2021-04-15 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0021_auto_20210404_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(max_length=100)),
                ('writer_name', models.CharField(choices=[('Professor 1', 'Dixon'), ('Professor 2', 'Johnson'), ('Professor 2', 'Eric')], max_length=100)),
                ('writer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_website', models.URLField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('company_recipients', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 15, 32, 51, 703855)),
        ),
    ]
