# Generated by Django 3.1.7 on 2021-04-24 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0022_auto_20210415_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 23, 32, 6, 537972)),
        ),
    ]
