# Generated by Django 3.1.7 on 2021-04-24 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0023_auto_20210423_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 1, 19, 6, 509982)),
        ),
    ]
