# Generated by Django 3.2 on 2021-04-27 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0024_auto_20210424_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 19, 31, 13, 293914)),
        ),
    ]
