# Generated by Django 3.1.7 on 2021-04-28 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0025_auto_20210426_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 12, 8, 28, 669821)),
        ),
    ]
