# Generated by Django 3.2 on 2021-04-27 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0025_alter_req_a_a_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 19, 44, 23, 227759)),
        ),
    ]
