# Generated by Django 3.1.7 on 2021-04-29 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0026_auto_20210428_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 21, 57, 42, 841344)),
        ),
    ]
