# Generated by Django 3.1.7 on 2021-04-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0027_auto_20210428_2157'),
        ('LOR', '0026_alter_req_a_a_date'),
    ]

    operations = [
    ]
