# Generated by Django 3.2 on 2021-05-02 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0027_auto_20210502_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 15, 33, 223804)),
        ),
    ]
