# Generated by Django 3.1.7 on 2021-04-29 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0029_auto_20210429_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 16, 57, 36, 234933)),
        ),
    ]
