# Generated by Django 3.1.7 on 2021-05-06 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0029_auto_20210502_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='writer_email',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='writer_name',
        ),
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 15, 48, 6, 815381)),
        ),
    ]
