# Generated by Django 3.1.7 on 2021-05-06 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOR', '0030_auto_20210506_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_a',
            name='A_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 15, 53, 3, 982009)),
        ),
    ]
