# Generated by Django 3.1.7 on 2021-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pdf',
            field=models.FileField(upload_to='Upload/pdf/'),
        ),
    ]
