# Generated by Django 3.1.7 on 2021-04-27 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moreinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 27, 19, 32, 1, 374031, tzinfo=utc))),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
