# Generated by Django 3.1.7 on 2021-04-27 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('more_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 19, 34, 11, 407668, tzinfo=utc)),
        ),
    ]
