# Generated by Django 3.1.7 on 2021-03-31 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name_title', models.CharField(max_length=25)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('WR', 'Writer'), ('RQ', 'Requester')], default='RQ', max_length=2)),
                ('position', models.CharField(max_length=100)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_baseuser_id', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=100)),
                ('request_initial_date', models.DateField()),
                ('request_final_date', models.DateField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_requester_id', to='Authentication.loruser')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_writer_id', to='Authentication.loruser')),
            ],
        ),
        migrations.CreateModel(
            name='LorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('RE', 'Resume'), ('TR', 'Transcript'), ('CV', 'CoverLetter'), ('AI', 'AdditionalInfo')], default='AI', max_length=2)),
                ('request_document', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_document_request_id', to='Authentication.lorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LorCompanyRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.URLField()),
                ('company_email', models.EmailField(max_length=254)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_recipient_request_id', to='Authentication.lorrequest')),
            ],
        ),
    ]
