# Generated by Django 3.1.7 on 2021-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20210331_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loruser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
